apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-zeta-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-zeta
  template:
    metadata:
      labels:
        app: server-zeta
    spec:
      containers:
      - name: server-zeta
        image: ajaff/zeta:alpine
        ports:
        - containerPort: 8282


---

apiVersion: v1
kind: Service
metadata:
  name: sserver-zeta-srv
spec:
  type: NodePort
  selector:
    app: server-zeta
  ports:
    - port: 8282
      targetPort: 8282
      nodePort: 32000

  
     